
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

project 'ModuleContainerExample.xcodeproj'

platform :ios, '8.0'

target 'ModuleContainerExample' do

   pod 'ModuleContainer' ,:path => '../../ModuleContainer.podspec'

end

